version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Benjamin15
      MYSQL_DATABASE: basededatospalabra
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./BD/database.sql:/docker-entrypoint-initdb.d/database.sql



  back8:
    build:
      context: ./Back  # Ajusta esto según tu estructura
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  front2:
    build:
      context: ./proyecto  # Ajusta esto según tu estructura
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - back8
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
