version: '3.8'

networks:
  backend-frontend:

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Benjamin15
      MYSQL_DATABASE: basededatospalabra
    ports:
      - "3306:3306"
    networks:
      - backend-frontend
    volumes:
      - ./BD/database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend-frontend
    depends_on:
      - mysql

  frontend:
    build:
      context: ./proyecto
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-frontend
