version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Benjamin15
      MYSQL_DATABASE: basededatospalabra
    ports:
      - "3306:3306"
    networks:
      - app-network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
