name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependencias
        run: pip install -r Back/requirements.txt

      - name: Instalar flask-cors (optional)
        run: pip install flask-cors  # Only needed if not in requirements.txt

      
        

      - name: Start database
        run: docker-compose up -d

      - name: Ejecutar tests unitarios
        run: python Back/Utests.py

      - name: Stop database
        run: docker-compose down
