name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build backend container
        run: docker build -t backend-image ./Back

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            backend-image \
            python /Back/Utests.py
