name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r Back/requirements.txt

      - name: Install flask-cors (optional)
        run: pip install flask-cors  # Only needed if not in requirements.txt
      - name: Start services
        run: docker-compose -f docker-compose.yml up -d
      - name: Run docker ps
        run: docker ps
        
      - name: Run unit tests
        run: python Back/Utests.py

      - name: Stop services
        run: docker-compose -f docker-compose.yml down
