name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5000)" != "200" ]; do
            echo "Backend service not ready yet, waiting..."
            sleep 1
          done


      - name: Copy Utest.py into backend container
        run: |
          docker cp Utest.py $(docker-compose ps -q backend):/Back/Utest.py

      - name: Run tests
        run: |
          docker-compose exec backend python /Back/Utest.py
