name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 

    services:
      basededatos:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Benjamin15
          MYSQL_DATABASE: basededatospalabra
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r Back/requirements.txt

      - name: Install flask-cors (optional)
        run: pip install flask-cors  # Only needed if not in requirements.txt

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Check service logs
        run: docker-compose -f docker-compose.yml logs basededatos

      - name: Get MySQL container IP
        run: echo "MySQL container IP: $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ingesw3final_basededatos_1)"

      - name: Run unit tests
        run: python Back/Utests.py

      - name: Stop services
        run: docker-compose -f Back/docker-compose.yml down
