name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build backend container
        run: docker build -t backend-image ./backend

      - name: Run tests
        run: |
          docker run --rm \
            -v $PWD/backend:/app \
            --network host \
            backend-image \
            python /app/Utests.py
