name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      basededatos:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Benjamin15
          MYSQL_DATABASE: basededatospalabra
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r Back/requirements.txt

      - name: Install flask-cors (optional)
        run: pip install flask-cors # Only needed if not in requirements.txt

      - name: Imprimir variable DB_HOST
        run: echo "La dirección del contenedor de la base de datos (DB_HOST) es: $DB_HOST"

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for MySQL to be ready
        run: docker-compose -f docker-compose.yml exec -T basededatos sh -c 'until mysqladmin ping -h localhost; do sleep 1; done'

      - name: Run unit tests
        run: python Back/Utests.py

      - name: Stop services
        run: docker-compose -f Back/docker-compose.yml down
